### ISSUE TITLE
New layout

### ISSUE THREAD

**Issue by jeanlucaslima** [xviniette/FlappyLearning#14]
Working on the new layout, any suggestions?

The idea is to have the controls panel on the right side, with some other options (such as kill current generation and others described on issues) and on top have the game info resumed. Ideas are welcome. 

![flappy](https://cloud.githubusercontent.com/assets/1311402/20237638/b420b9a8-a8bf-11e6-847a-3533d3c2e1ad.png)

**Comment by hojjatabdollahi** [comment]
I would love to see a visualization of the network. For example if we pause the game then we can see how many layers, how many neurons and their weights. That would be interesting. (For education purposes).
I also would like to see more parameters as input. For example if you could change the distance between the poles and feed the distance as an input to the network, that would be interesting.

**Comment by jeanlucaslima** [comment]
@hojjatabdollahi please, tell me all the parameters you can think of, it's the most important part.

**Comment by hojjatabdollahi** [comment]
@jeanleonino , In your current game everything is fixed, except the position of the gap in the pole.
So, if you change the gap size and the distance between the poles and feed these new parameters to your NN, then it would be more challenging.
Your code is efficient and impressive, good job. But I think feeding the actual position of the gap to your code is a kind of cheating. I think the final version of your code should use graphical input (just like a human) it makes it game-independent and your NN can learn to play new games.

**Comment by jeanlucaslima** [comment]
@hojjatabdollahi it's not my code, it's @xviniette's. But I'm improving the new version with ES6 to add these things. .

**Comment by wly2014** [comment]
@hojjatabdollahi may be this : https://github.com/yenchenlin/DeepLearningFlappyBird ,but it's not a Neuroevolution.
