### ISSUE TITLE
What is perception structure?

### ISSUE THREAD

**Issue by GospodinNoob** [xviniette/FlappyLearning#25]
What is perception structure? How it works? What are these paramentres doing?

**Comment by xviniette** [comment]
The perceptron is a type of neural network structure.

https://appliedgo.net/perceptron/
this website explain pretty well.

`network:[1 (a), [1] (b), 1 (c)]`
a : Number of neurons in the input layer
b : Array of number of neurons for each hidden layer
c : Number of neurons on the output layer

**Comment by GospodinNoob** [comment]
So, if i want to set in network 6 paramenters: a = 6 (for best result), and if i want to get a number: c = 1? And the neurons array looks like [6]? or not less then 6? Is it correct?

**Comment by xviniette** [comment]
The number of neurons on hidden layer will define the adaptability of your network. In general, (input + output)/2 is a good solution. 3 in your case.

**Comment by GospodinNoob** [comment]
Greate thanks!
