### ISSUE TITLE
Should add one more speed setting.

### ISSUE THREAD

**Issue by tarun7singh** [xviniette/FlappyLearning#7]
Project should have speed setting of "X10". Because once i was showing it took a lot of time to reach a good perfection level.

**Comment by kurtextrem** [comment]
for me, 31 generations were enough

**Comment by tarun7singh** [comment]
Once it took 43 generations and once only 4 generations and got perfect.

**Comment by tarun7singh** [comment]
Once it took 43 generations and once only 4 generations and got perfect.

**Comment by gediz** [comment]
Just add a `<button onclick="speed(600)">x10</button>` to the **index.html** after 12th line.

**Comment by tarun7singh** [comment]
Added the code.
